### PR TITLE
fix: changed kafka docker image version to a specific subversion

### PR DESCRIPTION
**Pull request by vijayg10**

### CODE REVIEW

**Comment by SharifMrCreed** [comment]
Ive managed to test it out. Kafka seems to be working well but the other services are not starting up. The central ledger fails to start with 127 error code.

Here is some of the log messages. Hope they can help 
```
[+] Running 12/0
 ✔ Container zookeeper                                           Running                                                                                                                                      0.0s
 ✔ Container ml-core-test-harness-mojaloop-testing-toolkit-ui-1  Running                                                                                                                                      0.0s
 ✔ Container kafka                                               Running                                                                                                                                      0.0s
 ✔ Container simulator                                           Running                                                                                                                                      0.0s
 ✔ Container ml-core-test-harness-mojaloop-testing-toolkit-1     Running                                                                                                                                      0.0s
 ✔ Container mysql-als                                           Running                                                                                                                                      0.0s
 ✔ Container objstore                                            Running                                                                                                                                      0.0s
 ✔ Container mysql                                               Running                                                                                                                                      0.0s
 ✔ Container central-ledger                                      Created                                                                                                                                      0.0s
 ✔ Container quoting-service                                     Created                                                                                                                                      0.0s
 ✔ Container account-lookup-service                              Created                                                                                                                                      0.0s
 ✔ Container ml-api-adapter                                      Created                                                                                                                                      0.0s
Attaching to account-lookup-service, central-ledger, kafka, ml-api-adapter, ml-core-test-harness-mojaloop-testing-toolkit-1, ml-core-test-harness-mojaloop-testing-toolkit-ui-1, ml-core-test-harness-ttk-provisioning-1, ml-core-test-harness-ttk-tests-1, mysql, mysql-als, objstore, quoting-service, simulator, zookeeper
': No such file or directory                        | env: can't execute 'node
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.148+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:45398","uuid":"7844d9e3-4892-46aa-8afc-7a9dd55f4e06","connectionId":153,"connectionCount":1}}
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.155+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn153","msg":"client metadata","attr":{"remote":"127.0.0.1:45398","client":"conn153","doc":{"application":{"name":"mongosh 1.8.2"},"driver":{"name":"nodejs|mongosh","version":"5.3.0|1.8.2"},"platform":"Node.js v16.19.1, LE","os":{"name":"linux","architecture":"x64","version":"5.10.16.3-microsoft-standard-WSL2","type":"Linux"}}}}
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.185+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:45400","uuid":"91fd015f-7d84-426b-8ddc-cadd9f9cecfb","connectionId":154,"connectionCount":2}}
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.185+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:45402","uuid":"53819924-8d88-4e54-9544-d98a1bf64f9b","connectionId":155,"connectionCount":3}}
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.187+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn154","msg":"client metadata","attr":{"remote":"127.0.0.1:45400","client":"conn154","doc":{"application":{"name":"mongosh 1.8.2"},"driver":{"name":"nodejs|mongosh","version":"5.3.0|1.8.2"},"platform":"Node.js v16.19.1, LE","os":{"name":"linux","architecture":"x64","version":"5.10.16.3-microsoft-standard-WSL2","type":"Linux"}}}}
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.189+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn155","msg":"client metadata","attr":{"remote":"127.0.0.1:45402","client":"conn155","doc":{"application":{"name":"mongosh 1.8.2"},"driver":{"name":"nodejs|mongosh","version":"5.3.0|1.8.2"},"platform":"Node.js v16.19.1, LE","os":{"name":"linux","architecture":"x64","version":"5.10.16.3-microsoft-standard-WSL2","type":"Linux"}}}}
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.205+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:45404","uuid":"7b14128a-80d3-4e25-8371-5de29ab74c0a","connectionId":156,"connectionCount":4}}
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.207+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn156","msg":"client metadata","attr":{"remote":"127.0.0.1:45404","client":"conn156","doc":{"application":{"name":"mongosh 1.8.2"},"driver":{"name":"nodejs|mongosh","version":"5.3.0|1.8.2"},"platform":"Node.js v16.19.1, LE","os":{"name":"linux","architecture":"x64","version":"5.10.16.3-microsoft-standard-WSL2","type":"Linux"}}}}
central-ledger exited with code 127
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.699+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn153","msg":"Interrupted operation as its client disconnected","attr":{"opId":6129}}
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.699+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn153","msg":"Connection ended","attr":{"remote":"127.0.0.1:45398","uuid":"7844d9e3-4892-46aa-8afc-7a9dd55f4e06","connectionId":153,"connectionCount":3}}
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.700+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn156","msg":"Connection ended","attr":{"remote":"127.0.0.1:45404","uuid":"7b14128a-80d3-4e25-8371-5de29ab74c0a","connectionId":156,"connectionCount":2}}
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.701+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn155","msg":"Connection ended","attr":{"remote":"127.0.0.1:45402","uuid":"53819924-8d88-4e54-9544-d98a1bf64f9b","connectionId":155,"connectionCount":1}}
objstore                                            | {"t":{"$date":"2023-05-29T17:36:59.701+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn154","msg":"Connection ended","attr":{"remote":"127.0.0.1:45400","uuid":"91fd015f-7d84-426b-8ddc-cadd9f9cecfb","connectionId":154,"connectionCount":0}}
': No such file or directory                        | env: can't execute 'node
': No such file or directory                        | env: can't execute 'node
': No such file or directory                        | env: can't execute 'node
dependency failed to start: container central-ledger exited (127)
```

**Comment by vijayg10** [comment]
> 

Hi @SharifMrCreed , what is your OS and machine configuration. It's working for me on macOS with apple silicon. I will test it in linux 64bit and check.

**Review by mdebarros — DISMISSED** [review]
+1

**Comment by mdebarros** [comment]
## Checkout commands for Windows

```
git clone -b fix/issues-with-kafka https://github.com/mojaloop/ml-core-test-harness.git
cd ml-core-test-harness
docker-compose --profile all-services --profile ttk-provisioning --profile ttk-tests up
```

## Provisioning Test Results:

```
--------------------FINAL REPORT--------------------


┌───────────────────────────────────────────────────┐

│                      SUMMARY                      │

├───────────────────┬───────────────────────────────┤

│ Total assertions  │ 84                            │

├───────────────────┼───────────────────────────────┤

│ Passed assertions │ 84                            │

├───────────────────┼───────────────────────────────┤

│ Failed assertions │ 0                             │

├───────────────────┼───────────────────────────────┤

│ Total requests    │ 82                            │

├───────────────────┼───────────────────────────────┤

│ Total test cases  │ 6                             │

├───────────────────┼───────────────────────────────┤

│ Passed percentage │ 100.00%                       │

├───────────────────┼───────────────────────────────┤

│ Started time      │ Thu, 01 Jun 2023 12:12:14 GMT │

├───────────────────┼───────────────────────────────┤

│ Completed time    │ 2023-06-01T12:12:34.628Z      │

├───────────────────┼───────────────────────────────┤

│ Runtime duration  │ 20225 ms                      │

└───────────────────┴───────────────────────────────┘
```

## Test Results

```
--------------------FINAL REPORT--------------------


┌───────────────────────────────────────────────────┐

│                      SUMMARY                      │

├───────────────────┬───────────────────────────────┤

│ Total assertions  │ 27                            │

├───────────────────┼───────────────────────────────┤

│ Passed assertions │ 27                            │

├───────────────────┼───────────────────────────────┤

│ Failed assertions │ 0                             │

├───────────────────┼───────────────────────────────┤

│ Total requests    │ 4                             │

├───────────────────┼───────────────────────────────┤

│ Total test cases  │ 1                             │

├───────────────────┼───────────────────────────────┤

│ Passed percentage │ 100.00%                       │

├───────────────────┼───────────────────────────────┤

│ Started time      │ Thu, 01 Jun 2023 12:12:37 GMT │

├───────────────────┼───────────────────────────────┤

│ Completed time    │ 2023-06-01T12:12:40.341Z      │

├───────────────────┼───────────────────────────────┤

│ Runtime duration  │ 2680 ms                       │

└───────────────────┴───────────────────────────────┘
```

**Review by mdebarros — APPROVED** [review]
+1

**Comment by vijayg10** [comment]
I tested this on Linux (Ubuntu 22.04.1 LTS AMD64, Docker version 20.10.22) and MacOS (Ventura 13.3.1 Apple M2 Max ARM64 Docker version 20.10.23) and its working on both machines.

**Output in Linux:**
```
ttk-tests_1                    | ┌───────────────────────────────────────────────────┐
ttk-tests_1                    | │                      SUMMARY                      │
ttk-tests_1                    | ├───────────────────┬───────────────────────────────┤
ttk-tests_1                    | │ Total assertions  │ 27                            │
ttk-tests_1                    | ├───────────────────┼───────────────────────────────┤
ttk-tests_1                    | │ Passed assertions │ 27                            │
ttk-tests_1                    | ├───────────────────┼───────────────────────────────┤
ttk-tests_1                    | │ Failed assertions │ 0                             │
ttk-tests_1                    | ├───────────────────┼───────────────────────────────┤
ttk-tests_1                    | │ Total requests    │ 4                             │
ttk-tests_1                    | ├───────────────────┼───────────────────────────────┤
ttk-tests_1                    | │ Total test cases  │ 1                             │
ttk-tests_1                    | ├───────────────────┼───────────────────────────────┤
ttk-tests_1                    | │ Passed percentage │ 100.00%                       │
ttk-tests_1                    | ├───────────────────┼───────────────────────────────┤
ttk-tests_1                    | │ Started time      │ Fri, 02 Jun 2023 09:44:52 GMT │
ttk-tests_1                    | ├───────────────────┼───────────────────────────────┤
ttk-tests_1                    | │ Completed time    │ 2023-06-02T09:44:54.670Z      │
ttk-tests_1                    | ├───────────────────┼───────────────────────────────┤
ttk-tests_1                    | │ Runtime duration  │ 1732 ms                       │
ttk-tests_1                    | └───────────────────┴───────────────────────────────┘
```

**Output in MacOS:**
```
ml-core-test-harness-ttk-tests-1                    | ┌───────────────────────────────────────────────────┐
ml-core-test-harness-ttk-tests-1                    | │                      SUMMARY                      │
ml-core-test-harness-ttk-tests-1                    | ├───────────────────┬───────────────────────────────┤
ml-core-test-harness-ttk-tests-1                    | │ Total assertions  │ 27                            │
ml-core-test-harness-ttk-tests-1                    | ├───────────────────┼───────────────────────────────┤
ml-core-test-harness-ttk-tests-1                    | │ Passed assertions │ 27                            │
ml-core-test-harness-ttk-tests-1                    | ├───────────────────┼───────────────────────────────┤
ml-core-test-harness-ttk-tests-1                    | │ Failed assertions │ 0                             │
ml-core-test-harness-ttk-tests-1                    | ├───────────────────┼───────────────────────────────┤
ml-core-test-harness-ttk-tests-1                    | │ Total requests    │ 4                             │
ml-core-test-harness-ttk-tests-1                    | ├───────────────────┼───────────────────────────────┤
ml-core-test-harness-ttk-tests-1                    | │ Total test cases  │ 1                             │
ml-core-test-harness-ttk-tests-1                    | ├───────────────────┼───────────────────────────────┤
ml-core-test-harness-ttk-tests-1                    | │ Passed percentage │ 100.00%                       │
ml-core-test-harness-ttk-tests-1                    | ├───────────────────┼───────────────────────────────┤
ml-core-test-harness-ttk-tests-1                    | │ Started time      │ Fri, 02 Jun 2023 09:45:54 GMT │
ml-core-test-harness-ttk-tests-1                    | ├───────────────────┼───────────────────────────────┤
ml-core-test-harness-ttk-tests-1                    | │ Completed time    │ 2023-06-02T09:46:03.732Z      │
ml-core-test-harness-ttk-tests-1                    | ├───────────────────┼───────────────────────────────┤
ml-core-test-harness-ttk-tests-1                    | │ Runtime duration  │ 9204 ms                       │
ml-core-test-harness-ttk-tests-1                    | └───────────────────┴───────────────────────────────┘
```

**Pull request merged**
